"""add_update_history_table

Revision ID: 13a4e683a360
Revises: 189756f3db4e
Create Date: 2026-01-27 20:32:24.307225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a4e683a360'
down_revision: Union[str, None] = '189756f3db4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_duty_schedule_id'), 'duty_schedule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duty_schedule_id'), table_name='duty_schedule')
    # ### end Alembic commands ###
