"""add_multiple_users_per_date_and_distribution_percentage

Revision ID: 19e6c33f26e2
Revises: 421a7b6616c8
Create Date: 2026-01-23 21:09:43.149623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e6c33f26e2'
down_revision: Union[str, None] = '421a7b6616c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Проверяем, существует ли таблица duty_schedule_users
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    if 'duty_schedule_users' not in tables:
        # Создаем таблицу duty_schedule_users перед удалением user_id
        op.create_table(
            'duty_schedule_users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('duty_schedule_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.ForeignKeyConstraint(['duty_schedule_id'], ['duty_schedule.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('duty_schedule_id', 'user_id', name='uq_duty_schedule_user')
        )
        op.create_index(op.f('ix_duty_schedule_users_id'), 'duty_schedule_users', ['id'], unique=False)
        
        # Мигрируем существующие данные из duty_schedule.user_id в duty_schedule_users
        try:
            result = connection.execute(sa.text("SELECT id, user_id FROM duty_schedule WHERE user_id IS NOT NULL"))
            for row in result:
                connection.execute(
                    sa.text("INSERT INTO duty_schedule_users (duty_schedule_id, user_id) VALUES (:schedule_id, :user_id)"),
                    {"schedule_id": row[0], "user_id": row[1]}
                )
        except Exception:
            pass  # Игнорируем ошибки при миграции данных
    
    # Проверяем, есть ли колонка user_id в duty_schedule
    columns = [col['name'] for col in inspector.get_columns('duty_schedule')]
    if 'user_id' in columns:
        # SQLite не поддерживает DROP COLUMN напрямую, нужно пересоздать таблицу
        op.drop_index('ix_duty_schedule_date', table_name='duty_schedule')
        
        # Создаем временную таблицу без user_id
        op.create_table(
            'duty_schedule_new',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('date', name='uq_duty_schedule_date')
        )
        
        # Копируем данные
        connection.execute(sa.text("INSERT INTO duty_schedule_new (id, date, created_at, updated_at) SELECT id, date, created_at, updated_at FROM duty_schedule"))
        
        # Удаляем старую таблицу
        op.drop_table('duty_schedule')
        
        # Переименовываем новую таблицу
        op.rename_table('duty_schedule_new', 'duty_schedule')
        
        # Создаем индекс
        op.create_index(op.f('ix_duty_schedule_date'), 'duty_schedule', ['date'], unique=False)
    
    # Проверяем, есть ли колонка distribution_percentage в entity_configs
    entity_columns = [col['name'] for col in inspector.get_columns('entity_configs')]
    if 'distribution_percentage' not in entity_columns:
        op.add_column('entity_configs', sa.Column('distribution_percentage', sa.Integer(), nullable=True, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_configs', 'distribution_percentage')
    op.add_column('duty_schedule', sa.Column('user_id', sa.INTEGER(), nullable=True))
    
    # Мигрируем данные обратно из duty_schedule_users в duty_schedule.user_id (берем первого пользователя)
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT duty_schedule_id, user_id FROM duty_schedule_users ORDER BY id"))
    for row in result:
        connection.execute(
            sa.text("UPDATE duty_schedule SET user_id = :user_id WHERE id = :schedule_id"),
            {"user_id": row[1], "schedule_id": row[0]}
        )
    
    op.alter_column('duty_schedule', 'user_id', nullable=False)
    op.create_foreign_key(None, 'duty_schedule', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_duty_schedule_date'), table_name='duty_schedule')
    op.create_index('ix_duty_schedule_date', 'duty_schedule', ['date'], unique=False)
    
    op.drop_index(op.f('ix_duty_schedule_users_id'), table_name='duty_schedule_users')
    op.drop_table('duty_schedule_users')
    # ### end Alembic commands ###
